<?php

use Illuminate\Database\Seeder;
use App\departamento;
use App\ciudad;

class departamentosyciudades extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $departamentos = ['Amazonas','Antioquia','Arauca','Atlántico','Bolívar','Boyacá','Caldas','Caquetá','Casanare','Cauca','Cesar','Chocó','Córdoba','Cundinamarca','Guainía','Guaviare','Huila','La Guajira','Magdalena','Meta','Nariño','Norte de Santander','Putumayo','Quindío','Risaralda','San Andrés y Providencia','Santander','Sucre','Tolima','Valle del Cauca','Vaupés','Vichada'];

        $ciudades = [
            [ 'El Encanto','La Chorrera','La Pedrera','La Victoria','Leticia','Mirití-Paraná','Puerto Alegría','Puerto Arica','Puerto Nariño','Puerto Santander','Tarapacá'],
            [ 'Cáceres',' Caucasia',' El Bagre',' Nechí',' Tarazá',' Zaragoza',' Caracolí',' Maceo',' Puerto Berrío',' Puerto Nare',' Puerto Triunfo',' Yondó',' Amalfi',' Anorí',' Cisneros',' Remedios',' San Roque',' Santo Domingo',' Segovia',' Vegachí',' Yalí',' Yolombó',' Angostura',' Belmira',' Briceño',' Campamento',' Carolina del Príncipe',' Donmatías',' Entrerríos',' Gómez Plata',' Guadalupe',' Ituango',' San Andrés de Cuerquia',' San José de la Montaña',' San Pedro de los Milagros',' Santa Rosa de Osos',' Toledo',' Valdivia',' Yarumal',' Abriaquí',' Antioquia',' Anzá',' Armenia',' Buriticá',' Caicedo',' Cañasgordas',' Dabeiba',' Ebéjico',' Frontino',' Giraldo',' Heliconia',' Liborina',' Olaya',' Peque',' Sabanalarga',' San Jerónimo',' Sopetrán',' Uramita',' Abejorral',' Alejandría',' Argelia',' Carmen de Viboral',' Cocorná',' Concepción',' El Peñol',' El Retiro',' El Santuario',' Granada',' Guarne',' Guatapé',' La Ceja',' La Unión',' Marinilla',' Nariño',' Rionegro',' San Carlos',' San Francisco',' San Luis',' San Rafael',' San Vicente',' Sonsón',' Amagá',' Andes',' Angelópolis',' Betania',' Betulia',' Caramanta',' Ciudad Bolívar',' Concordia',' Fredonia',' Hispania',' Jardín',' Jericó',' La Pintada',' Montebello',' Pueblorrico',' Salgar',' Santa Bárbara',' Támesis',' Tarso',' Titiribí',' Urrao',' Valparaíso',' Venecia',' Apartadó',' Arboletes',' Carepa',' Chigorodó',' Murindó',' Mutatá',' Necoclí',' San Juan de Urabá',' San Pedro de Urabá',' Turbo',' Vigía del Fuerte',' Barbosa',' Bello',' Caldas',' Copacabana',' Envigado',' Girardota',' Itagüí',' La Estrella',' Medellín',' Sabaneta' ],
            [ 'Arauca',' Arauquita','Cravo Norte','Fortul','Puerto Rondón','Saravena','Tame'],
            [ 'Barranquilla','Baranoa','Campo de la Cruz','Candelaria','Galapa','Juan de Acosta','Luruaco','Malambo',' Manatí','Palmar de Varela','Piojó','Polonuevo','Ponedera',' Puerto Colombia','Repelón','Sabanagrande','Sabanalarga','Santa Lucía',' Santo Tomás','Soledad','Suán','Tubará',' Usiacurí'],
            [ 'Achí',' Altos del Rosario',' Arenal',' Arjona',' Arroyohondo',' Barranco de Loba',' Calamar',' Cantagallo',' El Carmen de Bolívar',' Cartagena de Indias',' Cicuco',' Clemencia',' Córdoba',' El Guamo',' El Peñón',' Hatillo de Loba',' Magangué',' Mahates',' Margarita',' María La Baja',' Montecristo',' Morales',' Norosí',' Pinillos',' Regidor',' Río Viejo',' San Cristóbal',' San Estanislao',' San Fernando',' San Jacinto',' San Jacinto del Cauca',' San Juan Nepomuceno',' San Martín de Loba',' San Pablo',' Santa Catalina',' Santa Cruz de Mompox',' Santa Rosa',' Santa Rosa del Sur',' Simití',' Soplaviento',' Talaigua Nuevo',' Tiquisio',' Turbaco',' Turbaná',' Villanueva',' Zambrano'  ],
            [ 'Chíquiza',' Chivatá',' Cómbita',' Cucaita',' Motavita',' Oicatá',' Samacá',' Siachoque',' Sora',' Soracá',' Sotaquirá',' Toca',' Tunja',' Tuta',' Ventaquemada',' Chiscas',' El Cocuy',' El Espino',' Guacamayas',' Güicán',' Panqueba',' Labranzagrande',' Pajarito',' Paya',' Pisba',' Berbeo',' Campohermoso',' Miraflores',' Páez',' San Eduardo',' Zetaquira',' Boyacá',' Ciénega',' Jenesano',' Nuevo Colón',' Ramiriquí',' Rondón',' Tibaná',' Turmequé',' Úmbita',' Viracachá',' Chinavita',' Garagoa',' Macanal',' Pachavita',' San Luis de Gaceno',' Santa María',' Boavita',' Covarachía',' La Uvita',' San Mateo',' Sativanorte',' Sativasur',' Soatá',' Susacón',' Tipacoque',' Briceño',' Buenavista',' Caldas',' Chiquinquirá',' Coper',' La Victoria',' Maripí',' Muzo',' Otanche',' Pauna',' Quípama',' Saboyá',' San Miguel de Sema',' San Pablo de Borbur',' Tununguá',' Almeida',' Chivor',' Guateque',' Guayatá',' La Capilla',' Somondoco',' Sutatenza',' Tenza',' Arcabuco',' Chitaraque',' Gachantivá',' Moniquirá',' Ráquira',' Sáchica',' San José de Pare',' Santa Sofía',' Santana',' Sutamarchán',' Tinjacá',' Togüí',' Villa de Leyva',' Aquitania',' Cuítiva',' Firavitoba',' Gámeza',' Iza',' Mongua',' Monguí',' Nobsa',' Pesca',' Sogamoso',' Tibasosa',' Tópaga',' Tota',' Belén',' Busbanzá',' Cerinza',' Corrales',' Duitama',' Floresta',' Paipa',' Santa Rosa de Viterbo',' Tutazá',' Betéitiva',' Chita',' Jericó',' Paz de Río',' Socha',' Socotá',' Tasco',' Cubará',' Puerto Boyacá' ],
            [ 'Filadelfia',' La Merced',' Marmato',' Riosucio',' Supía',' Manzanares',' Marquetalia',' Marulanda',' Pensilvania',' Anserma',' Belalcázar',' Risaralda',' San José',' Viterbo',' Chinchiná',' Manizales',' Neira',' Palestina',' Villamaría',' La Dorada',' Norcasia',' Samaná',' Victoria',' Aguadas',' Aranzazu',' Pácora',' Salamina' ],
            [ 'Albania',' Belén de los Andaquies',' Cartagena del Chairá',' Curillo',' El Doncello',' El Paujil',' Florencia',' La Montañita',' Morelia',' Puerto Milán',' Puerto Rico',' San José del Fragua',' San Vicente del Caguán',' Solano',' Solita',' Valparaíso' ],
            [ 'Aguazul',' Chámeza',' Hato Corozal',' La Salina',' Maní',' Monterrey',' Nunchía',' Orocué',' Paz de Ariporo',' Pore',' Recetor',' Sabanalarga',' Sácama',' San Luis de Palenque',' Támara',' Tauramena',' Trinidad',' Villanueva',' Yopal' ],
            [ 'Buenos Aires',' Caloto',' Corinto',' Guachené',' Miranda',' Padilla',' Puerto Tejada',' Santander de Quilichao',' Suárez',' Villa Rica',' Cajibío',' El Tambo',' La Sierra',' Morales',' Piendamó',' Popayán',' Rosas',' Sotará',' Timbío',' Almaguer',' Argelia',' Balboa',' Bolívar',' Florencia',' La Vega',' Mercaderes',' Patía',' Piamonte',' San Sebastián',' Santa Rosa',' Sucre',' Guapí',' López de Micay',' Timbiquí',' Caldono',' Inzá',' Jambaló',' Páez',' Puracé (Coconuco)',' Silvia',' Toribío',' Totoró' ],
            [ 'Valledupar',' Aguachica',' Agustín Codazzi',' Bosconia',' Chimichagua',' El Copey',' San Alberto',' Curumaní',' El Paso',' La Paz',' Pueblo Bello',' La Jagua de Ibirico',' Chiriguaná',' Astrea',' San Martín',' Pelaya',' Pailitas',' Gamarra',' Manaure Balcón del Cesar',' Río de Oro',' Tamalameque',' Becerril',' San Diego',' La Gloria',' González',' Cesar' ],
            [ 'Acandí',' Alto Baudó',' Atrato',' Bagadó',' Bahía Solano',' Bajo Baudó',' Bojayá',' Cértegui',' Condoto',' El Cantón de San Pablo',' El Carmen de Atrato',' El Carmen del Darién',' El Litoral de San Juan',' Istmina',' Juradó',' Lloró',' Medio Atrato',' Medio Baudó',' Medio San Juan',' Nóvita',' Nuquí',' Quibdó',' Río Iró',' Río Quito',' Riosucio',' San José del Palmar',' Sipí',' Tadó',' Unguía',' Unión Panamericana' ],
            [ 'Ayapel',' Buenavista',' Canalete',' Cereté',' Chimá',' Chinú',' Ciénaga de Oro',' Cotorra',' La Apartada',' Los Córdobas',' Momil',' Montelíbano',' Montería',' Moñitos',' Planeta Rica',' Pueblo Nuevo',' Puerto Escondido',' Puerto Libertador',' Purísima',' Sahagún',' San Andrés de Sotavento',' San Antero',' San Bernardo del Viento',' San Carlos',' San José de Uré',' San Pelayo',' Santa Cruz de Lorica',' Tierralta',' Tuchín',' Valencia' ],
            [ 'Chocontá',' Machetá',' Manta',' Sesquilé',' Suesca',' Tibirita',' Villapinzón',' Agua de Dios',' Girardot',' Guataquí',' Jerusalén',' Nariño',' Nilo',' Ricaurte',' Tocaima',' Caparrapí',' Guaduas',' Puerto Salgar',' Albán',' La Peña',' La Vega',' Nimaima',' Nocaima',' Quebradanegra',' San Francisco',' Sasaima',' Supatá',' Útica',' Vergara',' Villeta',' Gachalá',' Gachetá',' Gama',' Guasca',' Guatavita',' Junín',' La Calera',' Ubalá',' Beltrán',' Bituima',' Chaguaní',' Guayabal de Síquima',' Pulí',' San Juan de Rioseco',' Vianí',' Medina',' Paratebueno',' Cáqueza',' Chipaque',' Choachí',' Fómeque',' Fosca',' Guayabetal',' Gutiérrez',' Quetame',' Ubaque',' Une',' El Peñón',' La Palma',' Pacho',' Paime',' San Cayetano',' Topaipí',' Villagómez',' Yacopí',' Cajicá',' Chía',' Cogua',' Gachancipá',' Nemocón',' Sopó',' Tabio',' Tenjo',' Tocancipá',' Zipaquirá',' Bojacá',' Cota',' El Rosal',' Facatativá',' Funza',' Madrid',' Mosquera',' Subachoque',' Zipacón',' Sibaté',' Soacha',' Arbeláez',' Cabrera',' Fusagasugá',' Granada',' Pandi',' Pasca',' San Bernardo',' Silvania',' Tibacuy',' Venecia',' Anapoima',' Anolaima',' Apulo',' Cachipay',' El Colegio',' La Mesa',' Quipile',' San Antonio del Tequendama',' Tena',' Viotá',' Carmen de Carupa',' Cucunubá',' Fúquene',' Guachetá',' Lenguazaque',' Simijaca',' Susa',' Sutatausa',' Tausa',' Ubaté' ],
            [ 'Barrancominas',' Cacahual',' Inírida',' La Guadalupe',' Mapiripana',' Morichal Nuevo',' Pana Pana',' Puerto Colombia',' San Felipe' ],
            [ 'Calamar',' El Retorno',' Miraflores',' San José del Guaviare' ],
            [ 'Aipe',' Algeciras',' Baraya',' Campoalegre',' Colombia',' Hobo',' Íquira',' Neiva',' Palermo',' Rivera',' Santa María',' Tello',' Teruel',' Villavieja',' Yaguará',' Agrado',' Altamira',' Garzón',' Gigante',' Guadalupe',' Pital',' Suaza',' Tarqui',' La Argentina',' La Plata',' Nátaga',' Paicol',' Tesalia',' Acevedo',' Elías',' Isnos',' Oporapa',' Palestina',' Pitalito',' Saladoblanco',' San Agustín',' Timaná' ],
            [ 'Albania',' Barrancas',' Dibulla',' Distracción',' El Molino',' Fonseca',' Hatonuevo',' La Jagua del Pilar',' Maicao',' Manaure',' Riohacha',' San Juan del Cesar',' Uribia',' Urumita',' Villanueva' ],
            [ 'Algarrobo',' Aracataca',' Ariguaní',' Cerro de San Antonio',' Chibolo',' Ciénaga',' Concordia',' El Banco',' El Piñón',' El Retén',' Fundación',' Guamal',' Nueva Granada',' Pedraza',' Pijiño del Carmen',' Pivijay',' Plato',' Pueblo Viejo',' Remolino',' Sabanas de San Ángel',' Salamina',' San Sebastián de Buenavista',' Santa Ana',' Santa Bárbara de Pinto',' Santa Marta',' San Zenón',' Sitionuevo',' Tenerife',' Zapayán',' Zona Bananera' ],
            [ 'Acacías',' Barranca de Upía',' Cabuyaro',' Castilla La Nueva',' Cubarral',' Cumaral',' El Calvario',' El Castillo',' El Dorado',' Fuente de Oro',' Granada',' Guamal',' La Macarena',' La Uribe',' Lejanías',' Mapiripán',' Mesetas',' Puerto Concordia',' Puerto Gaitán',' Puerto Lleras',' Puerto López',' Puerto Rico',' Restrepo',' San Carlos de Guaroa',' San Juan de Arama',' San Juanito',' San Martín',' Villavicencio',' Vista Hermosa' ],
            [ 'Barbacoas',' El Charco',' Francisco Pizarro (Salahonda)',' La Tola',' Magüí (Payán)',' Mosquera',' Olaya Herrera (Bocas de Satinga)',' Roberto Payán (San José)',' Santa Bárbara (Iscuandé)',' Tumaco',' Aldana',' Contadero',' Córdoba',' Cuaspud (Carlosama)',' Cumbal',' Funes',' Guachucal',' Gualmatán',' Iles',' Ipiales',' Potosí',' Puerres',' Pupiales',' Albán',' Arboleda (Berruecos)',' Belén',' Colón (Génova)',' El Rosario',' El Tablón de Gómez',' La Cruz',' La Unión',' Leiva',' Policarpa',' San Bernardo',' San Lorenzo',' San Pablo',' San Pedro de Cartago',' Taminango',' Buesaco',' Chachagüí',' Consacá',' El Peñol',' El Tambo',' La Florida',' Nariño',' Pasto',' Sandoná',' Tangua',' Yacuanquer',' Ancuyá',' Cumbitara',' Guaitarilla',' Imués',' La Llanada',' Linares',' Los Andes',' Mallama (Piedrancha)',' Ospina',' Providencia',' Ricaurte',' Samaniego',' Santacruz (Guachávez)',' Sapuyes',' Túquerres' ],
            [ 'Arboledas',' Cucutilla',' Gramalote',' Lourdes',' Salazar de Las Palmas',' Santiago',' Villa Caro',' Cúcuta',' El Zulia',' Los Patios',' Puerto Santander',' San Cayetano',' Villa del Rosario',' Bucarasica',' El Tarra',' Sardinata',' Tibú',' Ábrego',' Cáchira',' Convención',' El Carmen',' Hacarí',' La Esperanza',' La Playa de Belén',' Ocaña',' San Calixto',' Teorama',' Cácota',' Chitagá',' Mutiscua',' Pamplona',' Pamplonita',' Santo Domingo de Silos',' Bochalema',' Chinácota',' Durania',' Herrán',' Labateca',' Ragonvalia',' Toledo' ],
            [ 'Colón',' Mocoa',' Orito',' Puerto Asís',' Puerto Caicedo',' Puerto Guzmán',' Puerto Leguízamo',' San Francisco',' San Miguel',' Santiago',' Sibundoy',' Valle del Guamuez',' Villagarzón' ],
            [ 'Armenia',' Buenavista',' Calarcá',' Circasia',' Córdoba',' Filandia',' Génova',' La Tebaida',' Montenegro',' Pijao',' Quimbaya',' Salento' ],
            [ 'Apía',' Balboa',' Belén de Umbría',' Dosquebradas',' Guática',' La Celia',' La Virginia',' Marsella',' Mistrató',' Pereira',' Pueblo Rico',' Quinchía',' Santa Rosa de Cabal',' Santuario' ],
            [ 'San Andrés','Providencia','Santa Catalina' ],
            [ 'Aguada',' Albania',' Aratoca',' Barbosa',' Barichara',' Barrancabermeja',' Betulia',' Bolívar',' Bucaramanga',' Cabrera',' California',' Capitanejo',' Carcasí',' Cepitá',' Cerrito',' Charalá',' Charta',' Chima',' Chipatá',' Cimitarra',' Concepción',' Confines',' Contratación',' Coromoro',' Curití',' El Carmen de Chucurí',' El Guacamayo',' El Peñón',' El Playón',' Encino',' Enciso',' Florián',' Floridablanca',' Galán',' Gámbita',' Girón',' Guaca',' Guadalupe',' Guapotá',' Guavatá',' Güepsa',' Hato',' Jesús María',' Jordán',' La Belleza',' La Paz',' Landázuri',' Lebrija',' Los Santos',' Macaravita',' Málaga',' Matanza',' Mogotes',' Molagavita',' Ocamonte',' Oiba',' Onzaga',' Palmar',' Palmas del Socorro',' Páramo',' Piedecuesta',' Pinchote',' Puente Nacional',' Puerto Parra',' Puerto Wilches',' Rionegro',' Sabana de Torres',' San Andrés',' San Benito',' San Gil',' San Joaquín',' San José de Miranda',' San Miguel',' San Vicente',' Santa Bárbara',' Santa Helena del Opón',' Simacota',' Socorro',' Suaita',' Sucre',' Suratá',' Tona',' Valle de San José',' Vélez',' Vetas',' Villanueva',' Zapatoca' ],
            [ 'Guaranda',' Majagual',' Sucre',' Chalán',' Colosó',' Morroa',' Ovejas',' Sincelejo',' Coveñas',' Palmito',' San Onofre',' Santiago de Tolú',' Tolúviejo',' Buenavista',' Corozal',' El Roble',' Galeras',' Los Palmitos',' Sampués',' San Juan de Betulia',' San Pedro',' Sincé',' Caimito',' La Unión',' San Benito Abad',' San Marcos' ],
            [ 'Alvarado',' Anzoátegui',' Cajamarca',' Coello',' Espinal',' Flandes',' Ibagué',' Piedras',' Rovira',' San Luis',' Valle de San Juan',' Casabianca',' Herveo',' Lérida',' Líbano',' Murillo',' Santa Isabel',' Venadillo',' Villahermosa',' Ambalema',' Armero',' Falán',' Fresno',' Honda',' Mariquita',' Palocabildo',' Carmen de Apicalá',' Cunday',' Icononzo',' Melgar',' Villarrica',' Ataco',' Chaparral',' Coyaima',' Natagaima',' Ortega',' Planadas',' Rioblanco',' Roncesvalles',' San Antonio',' Alpujarra',' Dolores',' Guamo',' Prado',' Purificación',' Saldaña',' Suárez' ],
            [ 'Alcalá',' Andalucía',' Ansermanuevo',' Argelia',' Bolívar',' Buenaventura',' Buga',' Bugalagrande',' Caicedonia',' Cali',' Calima - El Darién',' Candelaria',' Cartago',' Dagua',' El Águila',' El Cairo',' El Cerrito',' El Dovio',' Florida',' Ginebra',' Guacarí',' Jamundí',' La Cumbre',' La Unión',' La Victoria',' Obando',' Palmira',' Pradera',' Restrepo',' Riofrío',' Roldanillo',' San Pedro',' Sevilla',' Toro',' Trujillo',' Tuluá',' Ulloa',' Versalles',' Vijes',' Yotoco',' Yumbo',' Zarzal' ],
            [ 'Carurú',' Mitú',' Pacoa',' Papunaua',' Taraira',' Yavaraté' ],
            [ 'Cumaribo',' La Primavera',' Puerto Carreño',' Santa Rosalía' ],
        ];

        $countDptos = count($departamentos);
        for($i=0;$i<$countDptos;$i++){
            $departamento = departamento::firstOrCreate(['name'=>$departamentos[$i], 'created_at' => date('Y-m-d H:i:s'),]);
            foreach ($ciudades[$i] as $municipio){
                ciudad::create(['name'=>$municipio, 'departamento_id'=>$departamento->id, 'created_at' => date('Y-m-d H:i:s'),]);
            }
        }
    }//fin de la funcion


}









